# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1whvAchL2yT6xkD7m6ensradRIDL68GXT
"""

file_path = "/content/input.txt"  # Replace with the actual path to your text file

# Read all lines from the file
with open(file_path, 'r') as file:
    lines = file.readlines()

# Replace "one" with "on1e" in each line
modified_lines = [line.replace('eight', 'eigh8t') for line in lines]

# Write the modified lines back to the file
with open(file_path, 'w') as file:
    file.writelines(modified_lines)

print(f'Replacement completed in {file_path}')